name: Automated tests

on:
  workflow_dispatch: # Добавляет возможность запуска с кнопки
    inputs:
      test_name: # Имя параметра
        description: "Choose test"
        required: true
        default: "test_first"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: first_test
        run: pytest -s -v
