name: Automated tests

on:
  workflow_dispatch:  # Запуск с кнопки в GitHub UI
    inputs:
      test_name:  # Параметр выбора теста
        description: "Choose a test to run"  # Описание
        required: true  # Сделать параметр обязательным
        default: "test_first"  # Значение по умолчанию для одного из тестов
        type: choice  # Тип ввода: выбор из списка
        options:
          - test_first
          - test_second  # Доступные опции
          - all_tests  # Опция для всех тестов

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run all tests
        if: ${{ github.event.inputs.test_name == 'all_tests' }}
        run: |
          echo "Running all tests"
          pytest -s -v tests/

      - name: Run selected test
        if: ${{ github.event.inputs.test_name != 'all_tests' }}
        run: |
          echo "Running test: ${{ github.event.inputs.test_name }}"
          pytest -s -v tests/first_tests/test_first.py::TestFirst::${{ github.event.inputs.test_name }}

